### ISSUE TITLE
can't verify that ad block extension is working

### ISSUE THREAD

**Issue by Aeva** [vain/lariza#19]
I didn't notice any difference navigating with it.  I added printf statement to extension and rebuilt to see if it initializes, but it did not print any of the test messages to the console.

**Comment by vain** [comment]
Can you tell me more about your setup? In particular, have you populated `~/.local/share/lariza/web_extensions` with a copy of or symlink to `we_adblock.so`? lariza only checks that directory for any `*.so` files and tries to load them as web extensions.

Furthermore, which version of WebKit2 are you compiling against?

**Comment by vain** [comment]
I just found your https://github.com/Aeva/webkit2gtk-experiment which mentions the hypothesis: "[maybe] extensions can't write to stdout?" Yes, they can. :) Simple printf statements show up in my terminal.

**Comment by Aeva** [comment]
Ah!  Sorry, I missed the symlink step.  Works fine now!  Thanks for your help :)
