### ISSUE TITLE
Download Manager Shows Incorrect Percentage 

### ISSUE THREAD

**Issue by githububub** [vain/lariza#23]
See http://oi64.tinypic.com/a2fcaq.jpg. This issue is repeatable.

**Comment by vain** [comment]
What's the deal with tinypic.com? Full of ads and popups. I copied your screenshot to a gist:

https://gist.github.com/vain/3952e2c153a0421e0a567b4cfc409088

As for your actual issue, please use Vi. SCNR. ;-)

I can reproduce the issue. From my point of view, this is a WebKit bug. Lariza connects to the signal `notify::estimated-progress` and then just calls `webkit_download_get_estimated_progress()`. [As documented](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitDownload.html#webkit-download-get-estimated-progress), this function should return a double value between `0.0` and `1.0`. For the file in question, I get `1.196078`.

The only thing I can do is clip this value into the (expected) range `[0, 1]`.

To get the real issue fixed, I suggest you open a bug report at the WebKit2GTK+ project. Would you be OK with that?

**Comment by githububub** [comment]
Lol. I have ads and popups blocked on tinypic.com so that the site appears neat and simple. Will file upstream. Thanks :)                                                                                                                                                                                                                                                                                                                                                                                                                    From: vainSent: Wednesday, December 14, 2016 07:44To: vain/larizaReply To: vain/larizaCc: GitHububub; AuthorSubject: Re: [vain/lariza] Download Manager Shows Incorrect Percentage (#23)What's the deal with tinypic.com? Full of ads and popups. I copied your screenshot to a gist:
https://gist.github.com/vain/3952e2c153a0421e0a567b4cfc409088
As for your actual issue, please use Vi. SCNR. ;-)
I can reproduce the issue. From my point of view, this is a WebKit bug. Lariza connects to the signal notify::estimated-progress and then just calls webkit_download_get_estimated_progress(). As documented, this function should return a double value between 0.0 and 1.0. For the file in question, I get 1.196078.
The only thing I can do is clip this value into the (expected) range [0, 1].
To get the real issue fixed, I suggest you open a bug report at the WebKit2GTK+ project. Would you be OK with that?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vain/lariza","title":"vain/lariza","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vain/lariza"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vain in #23: What's the deal with tinypic.com? Full of ads and popups. I copied your screenshot to a gist:\r\n\r\nhttps://gist.github.com/vain/3952e2c153a0421e0a567b4cfc409088\r\n\r\nAs for your actual issue, please use Vi. SCNR. ;-)\r\n\r\nI can reproduce the issue. From my point of view, this is a WebKit bug. Lariza connects to the signal `notify::estimated-progress` and then just calls `webkit_download_get_estimated_progress()`. [As documented](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitDownload.html#webkit-download-get-estimated-progress), this function should return a double value between `0.0` and `1.0`. For the file in question, I get `1.196078`.\r\n\r\nThe only thing I can do is clip this value into the (expected) range `[0, 1]`.\r\n\r\nTo get the real issue fixed, I suggest you open a bug report at the WebKit2GTK+ project. Would you be OK with that?"}],"action":{"name":"View Issue","url":"https://github.com/vain/lariza/issues/23#issuecomment-267068022"}}}
