### ISSUE TITLE
downloading .cgi files

### ISSUE THREAD

**Issue by music-fan** [vain/lariza#26]
Lariza downloads .cgi files instead of opening them in browser. For example: https://bugzilla.xfce.org/buglist.cgi?quicksearch=xfce4-session
The site works well with Firefox.

**Comment by vain** [comment]
Hum, works fine for me. Which version of WebKit2GTK are you using?

**Comment by music-fan** [comment]
2.14.2-2

**Comment by vain** [comment]
Okay, so that's a recent version on Arch Linux, I guess?

We'll probably have to dig into WebKit's code. Lariza calls `webkit_response_policy_decision_is_mime_type_supported()` (https://github.com/vain/lariza/blob/e69feb178971514fb88aeaf40ba918e78ea0d24c/browser.c#L381) to find out if a file is a "download" or if it has to be shown directly in the browser. So, we'll have to find out how that function works.

**Comment by Docbroke** [comment]
The link works fine with me, lariza displays the given link and I am using the same webkit2gtk 2.14.2-2 on archlinux. I guess issue may be with older version with lariza, as lariza/lairza-git in aur is 16.06. 

@music-fan can you update to lariza 16.12

**Comment by music-fan** [comment]
Fri, 13 Jan 2017 21:59:11 -0800 -n
Docbroke <notifications@github.com> írta:

> The link works fine with me, lariza displays the given link and I am using the same webkit2gtk 2.14.2-2 on archlinux. I guess issue may be with older version with lariza, as lariza/lairza-git in aur is 16.06. 
> 
> @music-fan can you update to lariza 16.12
> 


My lariza version is 16.12 (pacman -Qs lariza-git)

**Comment by vain** [comment]
@music-fan: Would you mind applying the following patch, so we can gather some more information?

    $ cd /tmp
    $ git clone https://github.com/vain/lariza.git
    $ wget https://gist.github.com/vain/0302b0a21bdb62d850cb55291d391ca5/raw/978ac5c55b30d4c1f55066455b7d5583c3359892/lariza-debug-statements.patch
    $ cd lariza
    $ patch -p1 <../lariza-debug-statements.patch

Now compile and run the browser directly from your terminal:

    $ make
    $ ./lariza -C 'https://bugzilla.xfce.org/buglist.cgi?quicksearch=xfce4-session'

Please provide the full terminal output after the page has finished loading.

What baffles me is that <https://bugzilla.xfce.org/buglist.cgi?quicksearch=xfce4-session> identifies as `text/html` on my system. That's just what I would expect. I'm very curious to see what your output looks like.

Are there any other pages that exhibit this problem?

**Comment by vain** [comment]
Another question: Do you use any web extensions? If yes, which ones?

**Comment by music-fan** [comment]
> Another question: Do you use any web extensions? If yes, which ones?
I don't use any extensions.

**Comment by music-fan** [comment]
> @music-fan: Would you mind applying the following patch, so we can gather some more information?
> 
>     $ cd /tmp
>     $ git clone https://github.com/vain/lariza.git
>     $ wget https://gist.github.com/vain/0302b0a21bdb62d850cb55291d391ca5/raw/978ac5c55b30d4c1f55066455b7d5583c3359892/lariza-debug-statements.patch
>     $ cd lariza
>     $ patch -p1 <../lariza-debug-statements.patch
> 
> Now compile and run the browser directly from your terminal:
> 
>     $ make
>     $ ./lariza -C 'https://bugzilla.xfce.org/buglist.cgi?quicksearch=xfce4-session'
> 
> Please provide the full terminal output after the page has finished loading.
> 
> What baffles me is that <https://bugzilla.xfce.org/buglist.cgi?quicksearch=xfce4-session> identifies as `text/html` on my system. That's just what I would expect. I'm very curious to see what your output looks like.
> 
> Are there any other pages that exhibit this problem?
> 

http://sprunge.us/ccFQ

**Comment by vain** [comment]
Oh boy, I should have seen that coming and should have included the *request* headers right from the start. I'll create a patch soon that adds this.

I'm still confused as to what's going on. Why would Xfce's bugzilla return a different mime type for you than it does for us? Are there any noteworthy oddities about your setup? Are you using a proxy of some kind? What's your version of libsoup? And let me repeat my previous question: Are there any other websites that show this problem?

**Comment by vain** [comment]
Also an important detail: Which user agent are you using? Did you change/set the environment variable `LARIZA_USER_AGENT`?

(I was assuming you use the default because you didn't mention it. But, well, you never know.)

**Comment by music-fan** [comment]
The user agent caused the problem. I had used it with the user agent of Firefox. I have changed it to the default user agent, and the site worked well, and also works well with any browser's user agent, which use WebKit2GTK+ engine (Safari, Opera, etc.).
