### ISSUE TITLE
open local html files

### ISSUE THREAD

**Issue by Docbroke** [vain/lariza#27]
```
lariza .w3m/bookmark.html
http://.w3m/bookmark.html
Error resolving '.w3m': Name or service not known
```

lariza tries to open local url with http, which prevents use of lariza to open local html files/ html mails from mutt.

**Comment by vain** [comment]
You have to specify a URI. For local files, this means adding a `file://` prefix:

    file:///home/docbroke/.w3m/bookmark.html

This prefix could be added automatically. We could check if a string entered in the input box is a valid local file. Sadly, this clashes with the text search function. :( A user entering `/tmp/foo` might either want to search for `tmp/foo` or to open the local file `/tmp/foo`. We can try to be "clever" here, but I'd really like to avoid this kind of ambiguity. If you want to open a local file, just add the `file://`.

**Comment by Docbroke** [comment]
Yes, I know that it works with "file:///" , but programs like mutt forwards html links like "/tmp/fjlkjk.html". Due to this I am not able to use lariza to open html mails from mutt.

**Comment by Docbroke** [comment]
Well, when I use `lariza /tmp/foo` from command line lariza automatically tries `http://`. There is no clash with search function, as entering `/tmp/foo` in location bar of lariza initiates search. 
I guess we can add `file:///`  prefix automatically when input is from command line and not entered in location bar, this function is already present for `http://`

**Comment by vain** [comment]
I'd like to keep a consistent behaviour, i.e. entering `/tmp/foo` should open the same thing, regardless of where you enter it (command line or input box).

But, yeah, you're right. This should be fixed. All browsers I know can open local files without the user having to prepend a `file://` -- even `surf` can do that.

**Comment by Docbroke** [comment]
and there is no point in searching for `tmp/foo` when input is from command line, as there is no webpage to initiate search for `tmp/foo`
