### ISSUE TITLE
Handler

### ISSUE THREAD

**Issue by beli3ver** [vain/lariza#29]
Is there a way to add a customer handler?
I want to add one like tg:// for Telegram?

Thanks

**Comment by Docbroke** [comment]
You can use lariza-external-handler, to open selected link with telegram.

**Comment by beli3ver** [comment]
How to use it?

**Comment by Docbroke** [comment]
for details look here https://github.com/vain/lariza/issues/25

In short, when you right click on a link you can select `open with external handler`, which will send the link url as `lariza-external-handler -u $url`, you need a executable script named lariza-external-handler in your path. Now what happens with the url depends on what you put in that script. 

Here are two examples of lariza-external-handler, you can modifty them to add telegram support
https://github.com/Docbroke/link_handler/blob/master/lariza-external-handler
https://github.com/vain/bin-pub/blob/master/browser-link-handler

**Comment by beli3ver** [comment]
Ok I think I am to stupid for it, I have this now:
`/home/malte/.confg/lariza/lariza-external-handler`

```bash
#!/bin/bash

# Either call from something like sxhkd to work on the current URI in
# the clipboard (i.e., preselect a command):
#
#     super + shift + c
#         browser-link-handler -c google-chrome-stable
#
# Or call from another program and preselect a URI, thus presenting
# dmenu to choose an action:
#
#     browser-link-handler -u http://www.vim.org
#
# When called without arguments, uses the URI in the clipboard and lets
# you choose an action.

ops=(
    google-chrome-stable
    sxiv
    gimp
    vlc
    trust-ssl-certificate
    wget
)

cmd=
uri=

while getopts c:u: name
do
  case $name in
        c) cmd=$OPTARG ;;
        u) uri=$OPTARG ;;
    esac
done

if [[ -z "$uri" ]]
then
    uri=$(xclip -o -selection clipboard)
fi

if (( "${#uri}" > 30 ))
then
    uri_short="${uri:0:15}…${uri:$((${#uri}-15))}"
else
    uri_short=$uri
fi

if [[ -z "$cmd" ]]
then
    cmd=$(for i in "${ops[@]}"; do echo "$i"; done |
          menu-wrapper -i -p "Run on URI '$uri_short':")
fi

case $cmd in
    google-chrome-stable)
        google-chrome-stable "$uri"
        ;;
    gimp)
        f=$(mktemp)
        curl -sLk "$uri" >"$f"
        gimp "$f"
        ;;
    vlc)
        terminal-wrapper -hold -e vlc "$uri"
        ;;
    sxiv)
        sxiv "$uri"
        ;;
    trust-ssl-certificate)
        terminal-wrapper -hold -e lariza-store-certificate "$uri"
        ;;
    wget)
        cd /tmp/tmp
        printf -v c %q "$uri"
        terminal-wrapper -e bash -c "wget $c; bash"
        ;;
esac
´´´
But how to used it in the PATH?

**Comment by Docbroke** [comment]
We have multiple issues here
1. It appears that you have just copied the file from Vain, but that wouldn't do as this file depends on few other Vain's own scripts, and it has no option for opening links with telegram. You will need your own script, depending on which applicatons you want to open your urls. For example, try this (you will need dmenu installed to use it)
```
#!/bin/bash
shopt -s lastpipe

ops=(
    telegram
   chromium )

option=$(for i in "${ops[@]}"; do echo "$i"; done |  dmenu -p  "open <u>$url</u> with...")

[[ ! $option ]] && exit
case "$option" in

chromium) chromium "$2" ;;
telegram) telegram-desktop "$2" ;;
*) $option "$2" ;;
esac
```

2. PATH is where you put all executables in your system. by default it includes /usr/bin, /usr/local/bin on most systems, check it with `echo $PATH` in your terminal. You can define path in your .bashrc if you want to add custom path like $HOME/bin (most users will do that or similar)

**Comment by beli3ver** [comment]
Ok, I have this now:

```bash
malte@DebLep:~$ echo $PATH
/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
malte@DebLep:~$ ls .bin/
lariza-external-handler
malte@DebLep:~$ cat .bin/lariza-external-handler 
#!/bin/bash
shopt -s lastpipe

ops=(
telegram
google-chrome )

option=$(for i in "${ops[@]}"; do echo "$i"; done |  dmenu -p  "open <u>$url</u> with...")

[[ ! $option ]] && exit
case "$option" in

  google-chrome) google-chrome "$2" ;;
  telegram) telegram "$2" ;;
  *) $option "$2" ;;
esac
malte@DebLep:~$ dme
dmenu       dmenu_path  dmenu_run
```
But when I use lariza and click right on a telegram link and thoose open with external handler, nothing happends.

**Comment by Docbroke** [comment]
what is /.bin?
path should be `/home/malte/.bin`
test it from terminal with
`lariza-external-handler -u www.google.com`

**Comment by beli3ver** [comment]
lol sorry there was a typo in `.profile` now it works.
thanks

**Comment by vain** [comment]
Just wanted to thank @Docbroke for helping! Much appreciated!

**Comment by beli3ver** [comment]
Yes, thanks so much and sorry for my stupid mistakes.

Am 28. Februar 2017 19:28:36 MEZ schrieb vain <notifications@github.com>:
>Just wanted to thank @Docbroke for helping! Much appreciated!
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/vain/lariza/issues/29#issuecomment-283122876

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Docbroke** [comment]
@vain , you can call this my way of saying thanks for creating this wonderful browser.
