### ISSUE TITLE
Libgcrypt warning: missing initialization - please fix the application

### ISSUE THREAD

**Issue by vain** [vain/lariza#37]
When starting lariza:

```
WebKitNetworkProcess[6303]: Libgcrypt warning: missing initialization - please fix the application
```

We don't use libgcrypt directly. Will have to investigate.

IIUC, this happens since the update to webkit2gtk 2.16.1-1.

**Comment by onodera-punpun** [comment]
This does not happen on CRUX. webkit2gtk 2.16.1, libgcrypt 1.7.6.

**Comment by vain** [comment]
One more thing ...

When launching lariza from a terminal, one might expect that this message would show up in that terminal. That's not true for me. I only see it in the console where I initially launched `startx`.

In other words, this is very easy to miss.

(My `.xinitrc` uses `systemd-cat` to send all this output to my journal, that's how I noticed.)

**Comment by vain** [comment]
Upstream bug:

https://bugs.webkit.org/show_bug.cgi?id=171230

Nothing for us to do here.
