### ISSUE TITLE
gtk_window_set_default_size() doesn't seem to do anything

### ISSUE THREAD

**Issue by onodera-punpun** [vain/lariza#42]
So I was writing some env variables to set the default size of a new window, but it seems like https://github.com/vain/lariza/blob/master/browser.c#L153 doesn't actually do anything. I tried to change the values to `1000, 1000` - no change. Completely removing the line also doesn't seem to make any impact.

It seems like tabbed causes this, with `-T` the line actually does make chance.

**Comment by onodera-punpun** [comment]
Fixed: https://github.com/vain/lariza/pull/43/files#diff-2b43b3fe77dd03f2ab5120fc7700ced0L1014

Alhough if you don't intend on merging the window size vars you could just remove the `gtk_window_set_default_size` line I suppose.

**Comment by vain** [comment]
tabbed's default window size is 800x600:

http://git.suckless.org/tabbed/tree/tabbed.c#n987

So, if that `gtk_window_set_default_size()` line is present, it doesn't matter if you start lariza with or without tabbed, you always get a 800x600 window by default.

(If I understand correctly, tabbed *cannot* know the "natural" size of its child windows, so it must enforce some arbitrary default size.)
