### ISSUE TITLE
Improve keyword based search 

### ISSUE THREAD

**Issue by notramo** [vain/lariza#46]
I use DuckDuckGo, because it has thousands of keywords (bangs) to search directly on sites.
That would be cool, if a text starts with a given character ( ! for bangs), Lariza should search with a given engine.
The difference is between my idea and the current keyword search is that the keyword have to be separated  from the search terms with a space, but in my idea it shouldn't, and the keyword would included in the search terms given to the engine.

**Comment by vain** [comment]
I'm not very familiar with DuckDuckGo, sorry. Can you elaborate? What's that exact string that you would wish to enter into the browser's input box?

CC #44, this is another use case.

**Comment by notramo** [comment]
I took a look on lariza-input-driver. It can do this, so implementing this feature in Lariza is not needed.
