### ISSUE TITLE
input-driver branch unusable

### ISSUE THREAD

**Issue by notramo** [vain/lariza#48]
If the program is compiled from the input-driver branch, it is unusable.
*edit: sorry, I used my old input-driver script, which only can use current uri, and entered text.*

I think the input-driver branch should be merged into master, because with a default installed lariza-input-driver script, it can behave as the master branch, but it allows a lot customization, and maintaining only one branch requires less work.

**Comment by vain** [comment]
Yeah, sorry, the `input-driver` branch is in a bit of flux. It's a development branch. I'm happy if anyone gives it a try to provide feedback -- but as long as it's not included in a release, things may change.

At the moment, there's a a 99% chance that the branch will eventually get merged into `master`. :-)
