### ISSUE TITLE
Homepage when opening browser

### ISSUE THREAD

**Issue by notramo** [vain/lariza#49]
Is there any opportunity to go to the homepage on browser startup (input-driver branch) ?
What about passing Alt+W automatically to lariza-input-driver on startup, or introduce a key (for example "browser_startup" in lariza-input-driver?

**Comment by vain** [comment]
How about launching the browser as `lariza $your_home_page` instead of a simple `lariza`? You can also make `$your_home_page` an environment variable that you can reuse in your input driver.

**Comment by notramo** [comment]
Launching ```lariza``` is easier than launching ```lariza $my_home_page```.

**Comment by vain** [comment]
Hmm, yeah, sure it is. Is that how you launch the program? You open a terminal or a dmenu and punch in `lariza` manually?

If you were using some kind of launcher/script/alias, it'd be trivial to add the home URI there.

**Comment by notramo** [comment]
I launch it from dmenu_run.

**Comment by vain** [comment]
I really believe that this should be implemented on a per-user basis. That is, write a little wrapper for launching lariza and add a corresponding hotkey to your input driver. (I, myself, have many launcher scripts like that for many different programs.)

After all, this is the whole point of the `input-driver` branch: Giving you, the user, more customization options. *This also puts you in charge.* Yes, this means that lariza is more and more becoming a "browser framework" like luakit or uzbl, although lariza is still *way* more minimalistic and will stay that way.
