### ISSUE TITLE
Zoom Not Working

### ISSUE THREAD

**Issue by martynjy** [vain/lariza#52]
HI vain

I have just installed lariza and I would like to say it is a nice little project.  It does just about all I want from a browser except the zoom function does not work for me.  Unless I have missed something!

**Comment by vain** [comment]
Hi and thanks. :-)

Zoom works fine for me. How exactly are you trying to zoom?

**Comment by martynjy** [comment]
I've tried all sorts of combinations but I read it as alt+arrow keys.

**Comment by vain** [comment]
Ahh, nope.

```
       Mod1 + Scroll up
       Ctrl + Scroll up
              Increase zoom level of the current page.

       Mod1 + Scroll down
       Ctrl + Scroll down
              Decrase zoom level of the current page.

       Mod1 + Scroll horizontally
       Ctrl + Scroll horizontally
              Reset zoom to $LARIZA_ZOOM.
```

"Scroll up" refers to the mouse wheel (or touchpad, trackpoint, whatever).

**Comment by martynjy** [comment]
Yes, that is what I though but I couldn't confirm it because mine is broken!  I've been using qutebrowser for some time and never use the scroll wheel.  Well I will have to get that new mouse.

Thanks for the quick responses.

**Comment by vain** [comment]
Okay then, going to close this. :-)
