### ISSUE TITLE
Thinking about relicensing under the MIT license

### ISSUE THREAD

**Issue by vain** [vain/lariza#53]
I'm thinking about changing the license from PIZZA-WARE to the MIT license:

https://choosealicense.com/licenses/mit/

The same has been done in sgopherd recently (https://github.com/vain/sgopherd/issues/2). It has been brought to my attention that PIZZA-WARE might sound like a fun idea, but it's [not optimal for the community](https://en.wikipedia.org/wiki/License_proliferation). Plus, I'm not a lawyer and PIZZA-WARE might have implications that I'm not aware of.

I think the MIT license is a good alternative. It basically grants the same rights as PIZZA-WARE (I don't want to impose new restrictions or anything like that), but it is very widespread and well understood.

There will be a new release. From that point on, it's MIT. The old code will stay PIZZA-WARE.

@onodera-punpun, @milouse: Both of you have contributed some code to this project. Please speak up during the next few weeks if you disagree with a switch to the MIT license.

Thank you!

**Comment by milouse** [comment]
I often publish my own work under the [WTFPL](http://www.wtfpl.net/), thus I was not bothered by the pizza-ware license. But I'll not be bothered too by a MIT or BSD change, as these license are very permissive. I do not care that much to the paternity of my contribution to your work, thus do what is important for you :)

**Comment by vain** [comment]
Alright, this is going to happen in the next release.

Haven't heard from @onodera-punpun yet. If you have any objections, please speak up. I think it'll be alright, though. :)
