### ISSUE TITLE
Use GAction instead of GtkAction

### ISSUE THREAD

**Issue by vain** [vain/lariza#54]
```
$ make
cc -Wall -Wextra -Wno-unused-parameter -O3  \
	-D__NAME__=\"lariza\" \
	-D__NAME_UPPERCASE__=\"`echo lariza | sed 's/.*/\U&/'`\" \
	-D__NAME_CAPITALIZED__=\"`echo lariza | sed 's/^./\U&\E/'`\" \
	-o lariza browser.c \
	`pkg-config --cflags --libs gtk+-3.0 glib-2.0 webkit2gtk-4.0`
browser.c: In function ‘menu_web_view’:
browser.c:929:9: warning: ‘gtk_action_new’ is deprecated [-Wdeprecated-declarations]
         action = gtk_action_new("external_handler", "Open with external handler",
         ^~~~~~
In file included from /usr/include/gtk-3.0/gtk/deprecated/gtkactivatable.h:25:0,
                 from /usr/include/gtk-3.0/gtk/gtk.h:248,
                 from browser.c:9:
/usr/include/gtk-3.0/gtk/deprecated/gtkaction.h:98:14: note: declared here
 GtkAction   *gtk_action_new                    (const gchar *name,
              ^~~~~~~~~~~~~~
browser.c:933:9: warning: ‘webkit_context_menu_item_new’ is deprecated: Use 'webkit_context_menu_item_new_from_gaction' instead [-Wdeprecated-declarations]
         mi = webkit_context_menu_item_new(action);
         ^~
In file included from /usr/include/webkitgtk-4.0/webkit2/WebKitContextMenu.h:28:0,
                 from /usr/include/webkitgtk-4.0/webkit2/webkit2.h:35,
                 from browser.c:13:
/usr/include/webkitgtk-4.0/webkit2/WebKitContextMenuItem.h:64:1: note: declared here
 webkit_context_menu_item_new                              (GtkAction              *action);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -Wall -Wextra -Wno-unused-parameter -O3  \
	-D__NAME__=\"lariza\" \
	-D__NAME_UPPERCASE__=\"`echo lariza | sed 's/.*/\U&/'`\" \
	-D__NAME_CAPITALIZED__=\"`echo lariza | sed 's/^./\U&\E/'`\" \
	-shared -o we_adblock.so -fPIC we_adblock.c \
	`pkg-config --cflags --libs glib-2.0 webkit2gtk-4.0`
```

**Comment by jun7** [comment]
Hi. I did it recently on my browser.
https://github.com/jun7/wyeb/commit/cad0648925a0b539420dbee3a3004af4322dabef

so like this?

	***GSimpleAction *action = NULL;
	WebKitContextMenuItem *mi = NULL;
	const gchar *uri = NULL;

	(void)ev;

	if (webkit_hit_test_result_context_is_link(ht))
		uri = webkit_hit_test_result_get_link_uri(ht);
	else if (webkit_hit_test_result_context_is_image(ht))
		uri = webkit_hit_test_result_get_image_uri(ht);
	else if (webkit_hit_test_result_context_is_media(ht))
		uri = webkit_hit_test_result_get_media_uri(ht);

	if (uri != NULL)
	{
		webkit_context_menu_append(menu, webkit_context_menu_item_new_separator());

		if (c->external_handler_uri != NULL)
			g_free(c->external_handler_uri);
		c->external_handler_uri = g_strdup(uri);
		***action = g_simple_action_new("external_handler", NULL);
		***g_signal_connect_swapped(G_OBJECT(action), "activate",
						 G_CALLBACK(external_handler_run), data);
		***mi = webkit_context_menu_item_new_from_gaction((GAction *)action, "external_handler", NULL);
		***g_object_unref(action);
and

	static void external_handler_run(gpointer);


Sorry I have not tested this, but only compiled.

**Comment by vain** [comment]
Oh, that looks very promising. Compiles and seems to work.

I'll push a patch in the next few days.

Thank you very much!
