### ISSUE TITLE
Export funktioniert mit Fluxbox Menü nicht

### ISSUE THREAD

**Issue by ghost** [vain/lariza#57]
Servus,

habe das in meiner **.bashrc** stehen:
```
export LARIZA_ACCEPTED_LANGUAGE=de-DE
export LARIZA_DOWNLOAD_DIR=/home/$USER/Downloads/
export LARIZA_HOME_URI=https://duckduckgo.com
export LARIZA_HISTORY_FILE=/home/$USER/.config/lariza/history
```
Wenn ich jetzt lariza über das terminal starte klappt das auch alles, wenn ich aber über das  Fluxbox Menü einbinde und starte, werden diese Variablen nicht geladen.
Ist das ein Bug von Debian, oder wie kann ich das beheben?

**Comment by vain** [comment]
Hi,

kommt darauf an, wie deine Fluxbox-„Session“ aufgebaut ist.

Ich persönlich mache das so, dass ich nach dem Booten erstmal nur an eine der Textkonsolen komme (tty1). Dort logge ich mich ein und bekomme eine interaktive Login-Shell. Dadurch wird meine `~/.bashrc` ausgewertet und die Variablen ähnlich wie bei dir gesetzt. Dann gebe ich `startx` ein (bzw. das tut die `~/.bashrc` automatisch, wenn es tty1 ist), dadurch kommt X ans Laufen und über die `~/.xinitrc` wird der Window-Manager und all das gestartet. Das heißt, dass bei mir jeder Prozess, den ich dann unter X starte, das Environment von dieser allerersten interaktiven Login-Shell erbt – somit auch lariza die Settings.

Da müsstest du jetzt mal bei dir gucken, wie dein Setup genau aussieht. Kann mir vorstellen, dass sowas wie ein grafischer Login-Manager eben kein solches initiales Environment aufbaut.

Im Zweifel kannst du natürlich immer ein kleines Wrapper-Skript schreiben, das erst die Variablen setzt und dann den Browser startet.

**Comment by ghost** [comment]
Habe es jetzt einfach in die autostart Datei von Fluxbox gemacht
Und jetzt rennt es, danke.
