### ISSUE TITLE
Add basic control bindings

### ISSUE THREAD

**Issue by josefnpat** [vain/lariza#8]
There are quite a few shortcuts missing that should probably be included;

CTRL-L - select URL
F5 - Refresh
SHIFT+F5 - Force refresh

**Comment by okraits** [comment]
I don't maintain my fork anymore so i deleted the repository. You might want to remove the link from the README then.
I also might quit my breasy project because i don't have time and interest in developing it anymore - and i bought a new laptop so i use firefox again.

**Comment by vain** [comment]
Sad to hear that. You could have left the code online but mark it as "unmaintained". :-)

(btw: I, too, have upgraded my laptop, hence the slightly reduced interest in lariza/breasy on my end. Nevertheless, I'll keep lariza alive.)

**Comment by okraits** [comment]
Yes, but i don't see a future for webkit (and the original lariza still exists anyway).
I would rather continue breasy based on QWebEngineView (chromium) than lariza based on webkit. But i simply don't have time and interest in developing my own browser right now - and firefox is too comfy :-)

On a side note: when i still developed breasy i discovered another possible base for a chromium-browser:

the chromium embedded framework: https://bitbucket.org/chromiumembedded/cef
